classroom/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin

from wagtail.admin import urls as wagtailadmin_urls
from wagtail.core import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls

from search import views as search_views

urlpatterns = [
    url(r'^django-admin/', admin.site.urls),

    url(r'^admin/', include(wagtailadmin_urls)),
    url(r'^documents/', include(wagtaildocs_urls)),

    url(r'^search/$', search_views.search, name='search'),

    url(r'^students/', include('students.urls'), name='students'),

    # For anything not caught by a more specific rule above, hand over to
    # Wagtail's page serving mechanism. This should be the last pattern in
    # the list:
    url(r'', include(wagtail_urls)),

    # Alternatively, if you want Wagtail pages to be served from a subpath
    # of your site, rather than the site root:
    #    url(r'^pages/', include(wagtail_urls)),
]


if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

students/urls.py
from django.conf.urls import url
from students import views

app_name='students'

urlpatterns = [
    url(r'^classes/$', views.class_list, name='class_list'),
    url(r'^attendances/$', views.attendance_list, name='attendance_list'),
]

home/models.py
from django.db import models

from modelcluster.fields import ParentalKey
from wagtail.admin.edit_handlers import (
    FieldPanel, FieldRowPanel,
    InlinePanel, MultiFieldPanel
)
from wagtail.core.fields import RichTextField
from wagtail.core.models import Page
from wagtail.contrib.forms.models import AbstractEmailForm, AbstractFormField
from wagtail.contrib.forms.edit_handlers import FormSubmissionsPanel

class HomePage(Page):
    pass

class FormField(AbstractFormField):
    page = ParentalKey('AboutUsPage', on_delete=models.CASCADE, related_name='form_fields')


class AboutUsPage(AbstractEmailForm):
    intro = RichTextField(blank=True)
    thank_you_text = RichTextField(blank=True)

    content_panels = AbstractEmailForm.content_panels + [
        FormSubmissionsPanel(),
        FieldPanel('intro', classname="full"),
        InlinePanel('form_fields', label="Form fields"),
        FieldPanel('thank_you_text', classname="full"),
        MultiFieldPanel([
            FieldRowPanel([
                FieldPanel('from_address', classname="col6"),
                FieldPanel('to_address', classname="col6"),
            ]),
            FieldPanel('subject'),
        ], "Email"),
    ]

students/models.py
from django.db import models

from modelcluster.fields import ParentalManyToManyField

from wagtail.core.models import Page
from wagtail.core.fields import RichTextField
from wagtail.admin.edit_handlers import FieldPanel
from wagtail.images.edit_handlers import ImageChooserPanel
from wagtail.search import index


class ClassPage(Page):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.slug = self.slug if self.slug else 'slug_will_be_generated_automatically'
    
    class_name = models.CharField(max_length=255)
    description = RichTextField(blank=True)
    
    content_panels = [
        FieldPanel('class_name', classname="full"),
        FieldPanel('description', classname="full"),
    ]
    
    search_fields = Page.search_fields + [
        index.SearchField('class_name'),
        index.SearchField('description'),
    ]

    def save(self, *args, **kwargs):
        self.title = self.class_name
        self.slug = "-".join(self.class_name.lower().split())
        super().save(*args, **kwargs)

class StudentPage(Page):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.slug = self.slug if self.slug else 'slug_will_be_generated_automatically'

    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    birthday = models.DateField()
    mobile_number = models.CharField(max_length=255)
    email = models.EmailField()
    comments = RichTextField(blank=True)
    image = models.ForeignKey('wagtailimages.Image', on_delete=models.SET_NULL, null=True, default=None, related_name='+')

    content_panels = [
        FieldPanel('first_name'),
        FieldPanel('last_name'),
        FieldPanel('birthday'),
        FieldPanel('mobile_number'),
        FieldPanel('email'),
        FieldPanel('comments'),
        ImageChooserPanel('image'),
    ]

    search_fields = Page.search_fields + [
        index.SearchField('first_name'),
        index.SearchField('last_name'),
        index.SearchField('mobile_number'),
        index.SearchField('email'),
        index.SearchField('comments'),
    ]

    def save(self, *args, **kwargs):
        self.title = self.first_name + " " + self.last_name
        self.slug = "-".join(self.title.lower().split())
        super().save(*args, **kwargs)

class AttendancePage(Page):
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.slug = self.slug if self.slug else 'slug_will_be_generated_automatically'

    date = models.DateField()
    students = ParentalManyToManyField(StudentPage, related_name='attendances')

    content_panels = [
        FieldPanel('date'),
        FieldPanel('students'),
    ]

    search_fields = Page.search_fields + [
        index.FilterField('date'),
        index.SearchField('students'),
    ]

    def save(self, *args, **kwargs):
        self.title = 'Att:' + str(self.date)
        self.slug = str(self.date)
        super().save(*args, **kwargs)

search/views.py
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

from wagtail.core.models import Page
from wagtail.search.models import Query

@login_required
def search(request):
    search_query = request.GET.get('query', None)
    page = request.GET.get('page', 1)

    # Search
    if search_query:
        search_results = Page.objects.live().search(search_query)
        query = Query.get(search_query)

        # Record hit
        query.add_hit()
    else:
        search_results = Page.objects.none()

    # Pagination
    paginator = Paginator(search_results, 10)
    try:
        search_results = paginator.page(page)
    except PageNotAnInteger:
        search_results = paginator.page(1)
    except EmptyPage:
        search_results = paginator.page(paginator.num_pages)

    return render(request, 'search/search.html', {
        'search_query': search_query,
        'search_results': search_results,
    })

students/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from students.models import ClassPage, AttendancePage

@login_required
def class_list(request):
    classes = ClassPage.objects.all()
    return render(request, 'students/class_list.html', {'classes':classes})

@login_required
def attendance_list(request):
    attendances = AttendancePage.objects.all()
    return render(request, 'students/attendance_list.html', {'attendances':attendances})

classroom/templates/base.html
{% load static wagtailuserbar wagtailcore_tags %}

<!DOCTYPE html>
<html class="no-js">
    <head>
        <meta charset="utf-8" />
        <title>
            {% block title %}
                {% if self.seo_title %}{{ self.seo_title }}{% else %}{{ self.title }}{% endif %}
            {% endblock %}
            {% block title_suffix %}
                {% with self.get_site.site_name as site_name %}
                    {% if site_name %}- {{ site_name }}{% endif %}
                {% endwith %}
            {% endblock %}
        </title>
        <meta name="description" content="" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        {# Global stylesheets #}
        <!-- bootstrap css -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootswatch/4.1.2/simplex/bootstrap.min.css">
        <!-- Custom global css         -->
        <link rel="stylesheet" type="text/css" href="{% static 'css/classroom.css' %}">
        {% block extra_css %}
            {# Override this in templates to add extra stylesheets #}
        {% endblock %}
    </head>

    <body class="{% block body_class %}{% endblock %}">
        {% wagtailuserbar %}
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="{% slugurl 'home' %}">ClassRoom</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
          
            <div class="collapse navbar-collapse" id="navbarColor01">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                  <a class="nav-link" href="{% slugurl 'home' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                {% if user.is_authenticated %}
                
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'wagtailadmin_home' %}">Admin</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'students:class_list' %}">Your Classes</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'students:attendance_list' %}">Attendance</a>
                </li>
                <li class="nav-item">
                        <a class="nav-link" href="{% url 'wagtailadmin_logout' %}">log out</a>
                </li>
                {% else %}
                <li class="nav-item">
                        <a class="nav-link" href="{% url 'wagtailadmin_login' %}">log in</a>
                </li>
                {% endif %}
                <li class="nav-item">
                  <a class="nav-link" href="{% slugurl 'about-us' %}">About</a>
                </li>
              </ul>
              <form class="form-inline my-2 my-lg-0" action="{% url 'search' %}" method="GET">
                <input class="form-control mr-sm-2" placeholder="Search" type="text" name="query">
                <input class="btn btn-secondary my-2 my-sm-0" type="submit" value="Search" />
              </form>
            </div>
          </nav>
        {% block content %}{% endblock %}

        {# Global javascript #}
        <script type="text/javascript" src="{% static 'js/classroom.js' %}"></script>

        {% block extra_js %}
            {# Override this in templates to add extra javascript #}
        {% endblock %}
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    </body>
</html>

home/templates/home/about_us_page.html
{% extends "base.html" %}
{% load wagtailcore_tags %}
{% load bootstrap4 %}
        
{% block content %}
<div class="container">
    <p></p>
    <title>{{ page.title }}</title>
    <h1>{{ page.title }}</h1>
    {{ page.intro|richtext }}
    <form action="{% pageurl page %}" method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input class="btn btn-primary" role="button" type="submit">
    </form>
    <p></p>
</div>
{% endblock content %}

home/templates/home/about_us_page_landing.html
{% extends "base.html" %}
{% load wagtailcore_tags %}

{% block content %}

<div class="container">
    <p></p>
    <div class="card">
        <div class="p-5">

            <h1>Thank you for contacting me!</h1>
            <h2>I will get back to you shortly.</h2>
            <h2>
                <a href="{% slugurl 'about-us' %}">Back</a>
            </h2>
        </div>
    </div>
</div>

{% endblock content %}

home/templates/home/home_page.html
{% extends "base.html" %}

{% block body_class %}template-homepage{% endblock %}

{% block content %}
<div class="container">
    <p></p>
    <div class="jumbotron">
        <h1>Welcome to ClassRoom!</h1>
        <p class="lead">A simple web application for helping teachers track their students in the Classroom</p>
        <hr class="my-4">
        <p>Written using Wagtail CMS</p>
        <div class="row">

          {% if user.is_authenticated %}
          <div class="col-lg-2 col-md-0">
          </div>
          <div class="col-lg-3 col-md-12">
            <a class="btn btn-primary btn-lg btn-block" href="{% url 'wagtailadmin_home' %}" role="button">Go to Admin Page</a>
          </div>
          <div class="col-lg-2 col-md-0"></div>
          <div class="col-lg-3 col-md-12">
            <a class="btn btn-primary btn-lg btn-block" href="{% url 'students:class_list' %}" role="button">Go to your classes</a>
          </div>
          <div class="col-lg-2 col-md-0">
          </div>
        </div>
        {% else %}
          <div class="col-lg-4 col-md-0">
          </div>
          <div class="col-lg-4 col-md-12">
              <a class="btn btn-primary btn-lg btn-block" href="{% url 'wagtailadmin_home' %}" role="button">Log In</a>
          </div>
          <div class="col-lg-4 col-md-0">
          </div>
        {% endif %}

      </div>
</div>
{% endblock %}

search/templates/search/search.html
{% extends "base.html" %}
{% load static wagtailcore_tags %}

{% block body_class %}template-searchresults{% endblock %}

{% block title %}Search{% endblock %}

{% block content %}
<div class="container">
    <p></p>
    <h2>Search Results:</h2>
    
    {% if search_results %}
    <ul>
        {% for result in search_results %}
        <li>
            <h4><a href="{% pageurl result %}">{{ result }}</a></h4>
            {% if result.search_description %}
            {{ result.search_description }}
            {% endif %}
        </li>
        {% endfor %}
    </ul>
    
    {% if search_results.has_previous %}
    <a href="{% url 'search' %}?query={{ search_query|urlencode }}&amp;page={{ search_results.previous_page_number }}">Previous</a>
    {% endif %}
    
    {% if search_results.has_next %}
    <a href="{% url 'search' %}?query={{ search_query|urlencode }}&amp;page={{ search_results.next_page_number }}">Next</a>
    {% endif %}
    {% elif search_query %}
    No results found
    {% endif %}
</div>
    {% endblock %}
    

students/templates/students/attendance_list.html
{% extends "base.html" %}
{% load wagtailcore_tags %}

{% block content %}

<div class="container">
<p></p>
<div class="card">
        <div class="card-body">
          <h4 class="card-title">Attendance List:</h4>
          <ul class="list-group list-group-flush">
              {% for attendance in attendances %}
              <a href="{% pageurl attendance %}">
                  <li class="list-group-item">{{ attendance.date }}</li>
              </a>
              {% endfor %}
          </ul>
        </div>
      </div>
</div>

{% endblock content %}

students/templates/students/attendance_page.html
{% extends "base.html" %}

{% load wagtailcore_tags wagtailimages_tags %}

{% block content %}

<div class="container">
    <p></p>
    <div class="card">
        <div class="card-body">
          <h4 class="card-title">Attendance on: {{ page.date }}</h4>
          <h6 class="card-subtitle mb-2 text-muted">Number of Students: {{ page.students.count }}</h6>
          <ul class="list-group list-group-flush">
            {% for student in page.students.all %}
            <a href="{% pageurl student %}">
                <li class="list-group-item">
                    <div class="row">
                        <div class="col-lg-3 col-md-6">
                        {{ student.first_name }} {{student.last_name}}
                        </div>
                        {% if student.image %}
                        <div class="col">
                        {% image student.image fill-50x50 style="border-radius: 50%;" %}
                        </div>            
                        {% endif %}
                    </div>
                    </li>

            </a>
            {% endfor %}
        </ul>
        </div>
      </div>

</div>

{% endblock content %}

students/templates/students/class_list.html
{% extends "base.html" %}
{% load wagtailcore_tags %}

{% block content %}

<div class="container">
<p></p>
<div class="card">
        <div class="card-body">
          <h4 class="card-title">List of your classes</h4>
          <ul class="list-group list-group-flush">
              {% for class in classes %}
              <a href="{% pageurl class %}">
                  <li class="list-group-item">{{ class.class_name }}</li>
              </a>
              {% endfor %}
          </ul>
        </div>
      </div>
</div>

{% endblock content %}

students/templates/students/class_page.html
{% extends "base.html" %}
{% load wagtailcore_tags wagtailimages_tags%}
{% block content %}
<div class="container">
    <p></p>
    <div class="card">
        <div class="card-body">
          <h4 class="card-title">{{ page.class_name }}</h4>
          <h6 class="card-subtitle mb-2">{{ page.description|richtext }}</h6>
          <b>Students List:</b>
          <ul class="list-group list-group-flush">
              {% for student in page.get_children %}
              <!-- just making sure that this is a student page -->
              {% if student.specific.first_name %} 
              <a href="{% pageurl student %}">
                  <li class="list-group-item">
                      <div class="row">
                          <div class="col-lg-3 col-md-6">
                              {{ student.specific.first_name }} {{ student.specific.last_name }}
                            </div>
                            {% if student.specific.image %}
                            <div class="col">
                                {% image student.specific.image fill-50x50 style="border-radius: 50%;" %}
                            </div>
                        </div>
                    </li>
                </a>
                            {% endif %}
                {% endif %}
              {% endfor %}
          </ul>
        </div>
      </div>
</div>
{% endblock content %}

students/templates/students/student_page.html
{% extends "base.html" %}

{% load wagtailcore_tags wagtailimages_tags %}

{% block content %}
<div class="container">
    <p></p>
    <div class="card">
        <div class="card-body">
          <h4 class="card-title">{{ page.first_name }} {{page.last_name}}</h4>
          <h6 class="card-subtitle mb-2 text-muted">{{ page.get_parent.class_name }}</h6>
          <div class="row">
            <div class="col-lg-3 col-md-6">
              <b>First Name:</b>
              <p class="card-text">{{ page.first_name }}</p>
              <b>Last Name:</b>
              <p class="card-text">{{ page.last_name }}</p>
            </div>
            {% if page.image %}
            <div class="col">
              {% image page.image fill-125x125 style="border-radius: 50%;" %}
            </div>
            {% endif %}
          </div>
          <b>Birthday:</b>
          <p class="card-text">{{ page.birthday }}</p>
          <b>Mobile Number:</b>
          <p class="card-text">{{ page.mobile_number }}</p>
          <b>Email:</b>
          <p class="card-text">{{ page.email }}</p>
          <b>Comments:</b>
          <p class="card-text">{{ page.comments|richtext }}</p>

          <a href="{{ page.get_parent.url }}" class="card-link">Go to student class</a>
        </div>
      </div>


</div>




{% endblock content %}

students/templates/students/student_profile_page.html
{% extends "base.html" %}

{% load wagtailcore_tags wagtailimages_tags %}

{% block content %}
<div class="container">
    <p></p>
    <div class="card">
        <div class="card-body">
          <h4 class="card-title">{{ page.first_name }} {{page.last_name}}</h4>
          <h6 class="card-subtitle mb-2 text-muted">{{ page.get_parent.class_name }}</h6>
          <div class="row">
            <div class="col-lg-3 col-md-6">
              <b>First Name:</b>
              <p class="card-text">{{ page.first_name }}</p>
              <b>Last Name:</b>
              <p class="card-text">{{ page.last_name }}</p>
            </div>
            {% if page.image %}
            <div class="col">
              {% image page.image fill-125x125 style="border-radius: 50%;" %}
            </div>
            {% endif %}
          </div>
          <b>Birthday:</b>
          <p class="card-text">{{ page.birthday }}</p>
          <b>Mobile Number:</b>
          <p class="card-text">{{ page.mobile_number }}</p>
          <b>Email:</b>
          <p class="card-text">{{ page.email }}</p>
          <b>Comments:</b>
          <p class="card-text">{{ page.comments|richtext }}</p>

          <a href="{{ page.get_parent.url }}" class="card-link">Go Back to class</a>
        </div>
      </div>


</div>




{% endblock content %}

students/templates/students/students_profiles_index_page.html
{% extends "base.html" %}
{% load wagtailcore_tags %}
{% block content %}
<div class="container">
    <p></p>
    <div class="card">
        <div class="card-body">
          <h4 class="card-title">{{ page.class_name }}</h4>
          <h6 class="card-subtitle mb-2">{{ page.description|richtext }}</h6>
          <b>Students List:</b>
          <ul class="list-group list-group-flush">
              {% for student in page.get_children %}
              <a href="{% pageurl student %}">
                  <li class="list-group-item">{{ student.specific.first_name }} {{ student.specific.last_name }}</li>
              </a>
              {% endfor %}
          </ul>
        </div>
      </div>
</div>
{% endblock content %}